plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-android-extensions'
    id 'kotlin-kapt'
}

android {
    compileSdk 32

    defaultConfig {
        minSdk 16
        targetSdk 32
        versionCode 7
        multiDexEnabled true
        flavorDimensions "default"
        resConfigs "en"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    productFlavors {
        production{
            applicationId "com.barikoi.cnlapp"
            dimension "default"
            //versionName "0.1.11"
            versionName "1.2.3"
            resValue "string", "app_name", "CNL SFA"
            resValue "string", "url_base", "https://cnl.barikoiretail.com:5623/"
            manifestPlaceholders = [
                    appIcon: "@mipmap/ic_launcher"
            ]
        }
        staging{
            applicationId "com.barikoi.cnlappstaging"
            dimension "default"
            versionName "1.2.2_3"
            resValue "string", "app_name", "CNL Staging SFA"
            //resValue "string", "url_base", "http://cnl.bkoih3.ml:7040/"
            resValue "string", "url_base", "http://20.24.15.52:7040/"
            manifestPlaceholders = [
                    appIcon: "@mipmap/ic_launcher_2"
            ]
        }
        retaildemo{
            applicationId "com.barikoi.retaildemo"
            dimension "default"
            versionName "0.0.2"
            resValue "string", "app_name", "Retail Demo SFA"
            //resValue "string", "url_base", "http://cnl.bkoih3.ml:7040/"
            resValue "string", "url_base", "http://20.24.15.52:2010/"
            manifestPlaceholders = [
                    appIcon: "@mipmap/ic_launcher_demo"
            ]
        }
        lalmairetaildemo{
            applicationId "com.barikoi.lalmairetaildemo"
            dimension "default"
            versionName "0.0.1"
            resValue "string", "app_name", "Lalmai Demo SFA"
            resValue "string", "url_base", "http://20.24.15.52:3051/"
            manifestPlaceholders = [
                    appIcon: "@mipmap/ic_launcher_lalmai"
            ]
        }
    }
    sourceSets {
        retaildemo {
            java {
                srcDirs 'src\\retaildemo\\java'
            }
        }
        staging {
            java {
                srcDirs 'src\\staging\\java'
            }
        }
        production {
            java {
                srcDirs 'src\\production\\java'
            }
        }
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.2'
    //implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    implementation 'com.google.android.material:material:1.5.0'
    //implementation "androidx.compose.material3:material3:1.7.0"

    implementation 'com.google.android.gms:play-services-places:17.0.0'
    implementation 'com.google.android.gms:play-services-location:19.0.0'

    implementation 'com.android.volley:volley:1.2.1'

    /*roomDB*/
    implementation "androidx.room:room-runtime:2.4.3"
    annotationProcessor "androidx.room:room-compiler:2.4.3"
    implementation 'androidx.lifecycle:lifecycle-livedata:2.5.1'
    kapt "androidx.room:room-compiler:2.2.4"
    kapt "androidx.room:room-runtime:2.2.4"

    /*map*/
    implementation 'org.maplibre.gl:android-sdk:9.2.1'
    //implementation 'com.github.maplibre:maplibre-navigation-android:1.1.1'

    /*progressbar*/
    implementation 'com.github.ybq:Android-SpinKit:1.4.0'

    implementation 'io.sentry:sentry-android:6.23.0'

    /*glide*/
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

    /*image zoom*/
    implementation 'com.commit451:PhotoView:1.2.4'

    //play store update
    implementation 'com.google.android.play:core:1.10.3'

    //heap autocapture session
    /*implementation 'io.heap.core:heap-android-core:0.1.0'
    implementation 'io.heap.autocapture:heap-autocapture-view:0.1.0'*/
}