plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'com.google.dagger.hilt.android'
    id 'kotlin-parcelize'
}

android {
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 23
        multiDexEnabled true
        flavorDimensions("default")
        resourceConfigurations += ['en', 'bn']
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField(
                "String",
                "ONESIGNAL_APP_ID",
                project.properties["ONESIGNAL_APP_ID"].toString()
        )
    }

    buildFeatures {
        buildConfig true
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        applicationVariants.all {
                // this method is use to rename your all apk weather
                // it may be signed or unsigned(debug apk)
            variant ->
                variant.outputs.each {
                        // on below line we are setting a
                        // name to our apk as GFG.apk
                    output ->
                        def name = "cnl_staging_debug_" + getDateTime() + ".apk"
                        // on below line we are setting the
                        // outputFile Name to our apk file.
                        output.outputFileName = name
                }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    productFlavors {
        production {
            applicationId "com.barikoi.cnlapp"
            dimension "default"
            versionName "1.2.7.13"
            resValue "string", "app_name", "CNL SFA"
            resValue "string", "url_base", "https://cnl.barikoiretail.com:5623/"

            buildConfigField "String", "TRACE_USER", project.properties["TRACE_USER"] as String
            buildConfigField "String", "TRACE_PASS", project.properties["TRACE_PASS"] as String
            buildConfigField "String", "TRACE_API_KEY", project.properties["BRU_TRACE_API_KEY"] as String

            buildConfigField "String", "TRACE_BASE_URL", project.properties["TRACE_BASE_URL_PROD"] as String

            buildConfigField "String", "url_base", '"https://cnl.barikoiretail.com:5623/"'
            buildConfigField 'String', 'sentryDNS', '"https://adc870f9532d8927d0203a60f35ef9ae@sentry.barikoimaps.dev/14"'
            manifestPlaceholders = [
                    appIcon  : "@mipmap/ic_launcher",
                    sentryDNS: "https://adc870f9532d8927d0203a60f35ef9ae@sentry.barikoimaps.dev/14",
//                    onesignal_app_id               : 'cf8bac16-674e-4f68-b587-63199f1b3053',
//                    onesignal_google_project_number: 'REMOTE'

            ]
        }
        staging {
            applicationId "com.barikoi.cnlappstaging"
            dimension "default"
            versionName "1.2.7.11_1"
            resValue "string", "app_name", "CNL Staging SFA"
            resValue "string", "url_base", "https://cnl.barikoimaps.dev/"
            buildConfigField "String", "url_base", '"https://cnl.barikoimaps.dev/"'

            buildConfigField "String", "TRACE_USER", project.properties["TRACE_USER"] as String
            buildConfigField "String", "TRACE_PASS", project.properties["TRACE_PASS"] as String
            buildConfigField "String", "TRACE_API_KEY", project.properties["TRACE_API_KEY"] as String

            buildConfigField "String", "TRACE_BASE_URL", project.properties["TRACE_BASE_URL_STAGING"] as String

            buildConfigField 'String', 'sentryDNS', '"https://9b5077bb9603abdd8a1562ff914b8790@sentry.barikoimaps.dev/13"'
            manifestPlaceholders = [
                    appIcon  : "@mipmap/ic_launcher_2",
                    sentryDNS: "https://9b5077bb9603abdd8a1562ff914b8790@sentry.barikoimaps.dev/13",
//                    onesignal_app_id               : 'cf8bac16-674e-4f68-b587-63199f1b3053',
//                    onesignal_google_project_number: 'REMOTE'

            ]
        }

        bruvanaStaging {
            applicationId "com.barikoi.bruvanastaging"
            dimension "default"
            versionName "1.2.7.11_1"
            resValue "string", "app_name", "Bruvana Staging SFA"
            resValue "string", "url_base", "https://bruvana.barikoiretail.com/"
            buildConfigField "String", "url_base", '"https://bruvana.barikoiretail.com/"'

            buildConfigField "String", "TRACE_USER", project.properties["BRU_TRACE_USER"] as String
            buildConfigField "String", "TRACE_PASS", project.properties["BRU_TRACE_PASS"] as String
            buildConfigField "String", "TRACE_API_KEY", project.properties["BRU_TRACE_API_KEY"] as String

            buildConfigField "String", "TRACE_BASE_URL", project.properties["TRACE_BASE_URL_STAGING"] as String
            buildConfigField 'String', 'sentryDNS', '"https://9b5077bb9603abdd8a1562ff914b8790@sentry.barikoimaps.dev/13"'
            manifestPlaceholders = [
                    appIcon  : "@mipmap/ic_launcher_2",
                    sentryDNS: "https://9b5077bb9603abdd8a1562ff914b8790@sentry.barikoimaps.dev/13",
//                    onesignal_app_id               : 'cf8bac16-674e-4f68-b587-63199f1b3053',
//                    onesignal_google_project_number: 'REMOTE'

            ]
        }

        bruvana {
            applicationId "com.barikoi.bruvana"
            dimension "default"
            versionName "1.2.7.11_1"
            resValue "string", "app_name", "Bruvana SFA Staging"
            resValue "string", "url_base", "https://bruvana.barikoiretail.com/"
            buildConfigField "String", "url_base", '"https://bruvana.barikoiretail.com/"'

            buildConfigField "String", "TRACE_USER", project.properties["BRU_TRACE_USER"] as String
            buildConfigField "String", "TRACE_PASS", project.properties["BRU_TRACE_PASS"] as String
            buildConfigField "String", "TRACE_API_KEY", project.properties["BRU_TRACE_API_KEY"] as String

            buildConfigField "String", "TRACE_BASE_URL", project.properties["TRACE_BASE_URL_STAGING"] as String
            buildConfigField 'String', 'sentryDNS', '"https://9b5077bb9603abdd8a1562ff914b8790@sentry.barikoimaps.dev/13"'
            manifestPlaceholders = [
                    appIcon  : "@mipmap/ic_launcher_2",
                    sentryDNS: "https://9b5077bb9603abdd8a1562ff914b8790@sentry.barikoimaps.dev/13",
//                    onesignal_app_id               : 'cf8bac16-674e-4f68-b587-63199f1b3053',
//                    onesignal_google_project_number: 'REMOTE'

            ]
        }

        retaildemo {
            applicationId "com.barikoi.retaildemo"
            dimension "default"
            versionName "0.0.3"
            resValue "string", "app_name", "Retail Demo SFA"
            //resValue "string", "url_base", "http://cnl.bkoih3.ml:7040/"
            resValue "string", "url_base", "http://20.24.15.52:2010/"
            manifestPlaceholders = [
                    appIcon: "@mipmap/ic_launcher_demo"
            ]
        }
        lalmairetaildemo {
            applicationId "com.barikoi.lalmairetaildemo"
            dimension "default"
            versionName "0.0.6"
            resValue "string", "app_name", "Lalmai Demo SFA"
            resValue "string", "url_base", "https://cnl.barikoiretail.com:4823/"
            manifestPlaceholders = [
                    appIcon: "@mipmap/ic_launcher_lalmai"
            ]
        }
    }
    sourceSets {
        retaildemo {
            java {
                srcDirs 'src\\retaildemo\\java'
            }
        }
        staging {
            java {
                srcDirs 'src\\staging\\java'
            }
        }
        production {
            java {
                srcDirs 'src\\production\\java'
            }
        }
    }
    namespace 'com.barikoi.cnlapp'
}

def getDateTime() {
    return new Date().format('yyyy-MM-dd_HH-mm-ss')
}

kapt {
    correctErrorTypes true
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.compose.ui:ui-text-android:1.7.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    implementation 'com.google.android.material:material:1.12.0'

    implementation 'com.google.android.gms:play-services-places:17.1.0'
    implementation 'com.google.android.gms:play-services-location:21.3.0'

    implementation 'com.android.volley:volley:1.2.1'

    /*shared prefs*/
    implementation 'androidx.preference:preference-ktx:1.2.1'

    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.8.6'
    implementation 'androidx.fragment:fragment-ktx:1.8.4'

    /*roomDB*/
    implementation "androidx.room:room-runtime:2.6.1"
    //noinspection KaptUsageInsteadOfKsp
    kapt "androidx.room:room-compiler:2.6.1"
    implementation "androidx.room:room-ktx:2.6.1"

    /*map*/
    implementation 'org.maplibre.gl:android-sdk:10.2.0'

    /*progressbar*/
    implementation 'com.github.ybq:Android-SpinKit:1.4.0'

    implementation 'io.sentry:sentry-android:7.9.0'

    /*glide*/
    implementation 'com.github.bumptech.glide:glide:4.14.2'
    kapt 'com.github.bumptech.glide:compiler:4.12.0'

    /*image zoom*/
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'

    //play store update
    implementation 'com.google.android.play:app-update:2.1.0'

    /*barikoi trace-sdk*/
    implementation 'com.github.barikoi:Barikoitrace-android-sdk:0.3.0'

    // HILT
    implementation "com.google.dagger:hilt-android:2.51.1"
    kapt "com.google.dagger:hilt-compiler:2.51.1"


    // Retrofit
    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.retrofit2:converter-gson:2.11.0")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")

    implementation("com.onesignal:OneSignal:5.1.17")
    implementation 'com.github.esafirm:android-image-picker:3.1.0'
    implementation('io.socket:socket.io-client:2.1.0') {
        exclude group: 'org.json', module: 'json'
    }
    implementation 'com.jakewharton.threetenabp:threetenabp:1.3.1'

    implementation("io.coil-kt.coil3:coil:3.0.0")
    implementation("io.coil-kt.coil3:coil-network-okhttp:3.0.0")

    implementation("id.zelory:compressor:3.0.1")
}